
# tap repositories and their packages

tap caskroom/cask
cask aquaterm
cask cuda
cask java
cask xquartz

tap homebrew/core
brew autoconf
brew automake
brew bazel
brew cloog
brew cmake
brew coreutils
brew ctags
brew doxygen
brew gcc
brew gd
brew gdbm
brew ghostscript
brew gl2ps
brew gmp
brew gnuplot --with-aquaterm --with-x11
brew imagemagick
brew libevent
brew libtool
brew libusb --universal
brew lua
brew mas
brew mongodb
brew mysql
brew nkf
brew node
brew openexr
brew openssl
brew osxutils
brew pcre
brew pkg-config
brew plotutils
brew pwgen
brew rbenv
brew readline
brew ruby-build
brew tmux
brew tree
brew vim --with-lua
brew wget

tap homebrew/python
brew numpy

tap homebrew/science
brew arpack
brew glpk
brew hdf5
brew octave
brew opencv
brew qhull
brew qrupdate
brew suite-sparse421
brew veclibfort

tap homebrew/versions

tap rcmdnk/file
brew brew-file

tap argon/mas

# App Store applications
appstore 406056744 Evernote
appstore 425955336 Skitch
appstore 425424353 The Unarchiver
