[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'haya14busa/vim-gtrans'

[[plugins]]
repo = 'nvie/vim-flake8'

[[plugins]]
repo = 'vim-syntastic/syntastic'

