[[plugins]]
repo = 'Shougo/dein.vim'

#[[plugins]]
#repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'nvie/vim-flake8'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'kana/vim-operator-user'
